### ISSUE TITLE
clean:config

### ISSUE THREAD

**Issue by brol** [JcDenis/dcAdvancedCleaner#1]
je me disais que ça serait bien d'ajouter dans ton plugin celui de Moe (que tu trouveras chez moi) et qui permet de supprimer des réglages des plugins sans supprimer pour autant les plugins. ça serait un chouette complément, non ?

**Comment by JcDenis** [comment]
dcAdvancedCleaner permet déjà de supprimer tous les paramètres (en global ou pour un blog) d'un plugin, d'un coup. Ici tu parles de pouvoir le faire paramètre par paramètre ?
Si oui, il faut que je regarde si ça ne complique pas trop le plugin car ça va rajouter pas mal de code pour _rentrer_ dans le détail d'un plugin.

**Comment by brol** [comment]
> Ici tu parles de pouvoir le faire paramètre par paramètre ?

voui, c'est ce que fait clean config
