### ISSUE TITLE
demande unisntaller

### ISSUE THREAD

**Issue by nanart59** [JcDenis/dcAdvancedCleaner#3]
Bonjour,
Message: `Advanced cleaner : Requiert le module Uninstaller qui n'est pas installé`
Je ne trouve pas Uninstaller  sur le dépot dotclear; peut-être sous un autre nom ?

nb: ce serait bien d'indiquer dans Readme que ce plug est demandé pour l'install de Advanced cleaner  ?

**Comment by JcDenis** [comment]
C'est compliqué ! (enfin un peu)

Effectivement je vais modifier le README pour dire qu'il faut ce plugin. Par contre il n'est pas sur Dotaddict car il sera peut-être inclus d'office dans la prochaine version de dotclear, donc pour l'instant il n'est dispo que sur mon github.

Si besoin, il est dispo là: [https://github.com/JcDenis/Uninstaller](https://github.com/JcDenis/Uninstaller)

**Comment by JcDenis** [comment]
Au dernière nouvelle il devrait être inclue pour la 2.28 d'automne.
